# analysis_options.yaml

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Defina regras adicionais aqui conforme necessário
    - always_specify_types: true
    - avoid_print: true
    - prefer_final_locals: true
    - prefer_const_constructors: true
    - prefer_const_literals_to_create_immutables: true
    - avoid_function_literals_in_foreach_calls: true
    - lines_longer_than_80_chars: true

analyzer:
  enable-experiment:
    - non-nullable

  strong-mode: true
  exclude:
    - lib/generated_plugin_registrant.dart
